/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.menus;

import vistas.consultas.Listado3;
import vistas.consultas.Listado2;
import vistas.consultas.Listado6;
import vistas.consultas.Listado1;
import vistas.consultas.Listado5;
import vistas.consultas.Listado4;
import vistas.*;

/**
 *
 * @author Jess
 */
public class MenuListados extends javax.swing.JFrame {
    Listado1 L1 = new Listado1();
    Listado2 L2 = new Listado2();
    Listado3 L3 = new Listado3();
    Listado4 L4 = new Listado4();
    Listado5 L5 = new Listado5();
    Listado6 L6 = new Listado6();
   
    /**
     * Creates new form IngresarDatos
     */
    public MenuListados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelColegio1 = new javax.swing.JPanel();
        Title2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        idColegio2 = new javax.swing.JTextField();
        nombreColegio1 = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Title3 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        idColegio3 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Panelmenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        volver = new javax.swing.JButton();
        listado1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        listado2 = new javax.swing.JButton();
        listado3 = new javax.swing.JButton();
        listado4 = new javax.swing.JButton();
        listado5 = new javax.swing.JButton();
        listado6 = new javax.swing.JButton();

        PanelColegio1.setBackground(new java.awt.Color(255, 255, 255));

        Title2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title2.setText("Datos Colegio");
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Id Colegio");

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));

        idColegio2.setForeground(new java.awt.Color(102, 102, 102));
        idColegio2.setText("Ingresar id del colegio");
        idColegio2.setBorder(null);
        idColegio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idColegio2MousePressed(evt);
            }
        });

        nombreColegio1.setForeground(new java.awt.Color(102, 102, 102));
        nombreColegio1.setText("Ingresar nombre del colegio");
        nombreColegio1.setBorder(null);
        nombreColegio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreColegio1MousePressed(evt);
            }
        });
        nombreColegio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreColegio1ActionPerformed(evt);
            }
        });

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Nombre del Colegio");

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));

        Title3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title3.setText("Datos Uniforme");
        Title3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Id Colegio");

        idColegio3.setForeground(new java.awt.Color(102, 102, 102));
        idColegio3.setText("Ingresar id del colegio");
        idColegio3.setBorder(null);
        idColegio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idColegio3MousePressed(evt);
            }
        });

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));

        javax.swing.GroupLayout PanelColegio1Layout = new javax.swing.GroupLayout(PanelColegio1);
        PanelColegio1.setLayout(PanelColegio1Layout);
        PanelColegio1Layout.setHorizontalGroup(
            PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColegio1Layout.createSequentialGroup()
                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Text7)
                                .addComponent(nombreColegio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Text6)
                                .addComponent(idColegio2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegio1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title2)
                        .addGap(80, 80, 80)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelColegio1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(Title3))
                            .addGroup(PanelColegio1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text8)
                                    .addComponent(idColegio3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelColegio1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGap(308, 308, 308)))
        );
        PanelColegio1Layout.setVerticalGroup(
            PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColegio1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addComponent(Title3)
                        .addGap(18, 18, 18)
                        .addComponent(Text8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idColegio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addComponent(Title2)
                        .addGap(18, 18, 18)
                        .addComponent(Text6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idColegio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Text7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreColegio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelColegio1Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(163, 150));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(844, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelmenu.setBackground(new java.awt.Color(51, 51, 51));
        Panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lupa.png"))); // NOI18N
        jLabel1.setText("   Menú Consultar");
        Panelmenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 46));
        Panelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 10));

        volver.setBackground(new java.awt.Color(21, 101, 192));
        volver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("Volver");
        volver.setBorder(null);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        Panelmenu.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 140, 30));

        listado1.setBackground(new java.awt.Color(51, 51, 51));
        listado1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listado1.setForeground(new java.awt.Color(255, 255, 255));
        listado1.setText("Listado 1");
        listado1.setAlignmentY(0.0F);
        listado1.setBorder(null);
        listado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listado1.setFocusPainted(false);
        listado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listado1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listado1MouseExited(evt);
            }
        });
        listado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado1ActionPerformed(evt);
            }
        });
        Panelmenu.add(listado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_listados.png"))); // NOI18N
        Panelmenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 120));

        listado2.setBackground(new java.awt.Color(51, 51, 51));
        listado2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listado2.setForeground(new java.awt.Color(255, 255, 255));
        listado2.setText("Listado 2");
        listado2.setAlignmentY(0.0F);
        listado2.setBorder(null);
        listado2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listado2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listado2MouseExited(evt);
            }
        });
        listado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado2ActionPerformed(evt);
            }
        });
        Panelmenu.add(listado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 30));

        listado3.setBackground(new java.awt.Color(51, 51, 51));
        listado3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listado3.setForeground(new java.awt.Color(255, 255, 255));
        listado3.setText("Listado 3");
        listado3.setAlignmentY(0.0F);
        listado3.setBorder(null);
        listado3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listado3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listado3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listado3MouseExited(evt);
            }
        });
        listado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado3ActionPerformed(evt);
            }
        });
        Panelmenu.add(listado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 30));

        listado4.setBackground(new java.awt.Color(51, 51, 51));
        listado4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listado4.setForeground(new java.awt.Color(255, 255, 255));
        listado4.setText("Listado 4");
        listado4.setAlignmentY(0.0F);
        listado4.setBorder(null);
        listado4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listado4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listado4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listado4MouseExited(evt);
            }
        });
        listado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado4ActionPerformed(evt);
            }
        });
        Panelmenu.add(listado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 30));

        listado5.setBackground(new java.awt.Color(51, 51, 51));
        listado5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listado5.setForeground(new java.awt.Color(255, 255, 255));
        listado5.setText("Listado 5");
        listado5.setAlignmentY(0.0F);
        listado5.setBorder(null);
        listado5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listado5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listado5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listado5MouseExited(evt);
            }
        });
        listado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado5ActionPerformed(evt);
            }
        });
        Panelmenu.add(listado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 30));

        listado6.setBackground(new java.awt.Color(51, 51, 51));
        listado6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listado6.setForeground(new java.awt.Color(255, 255, 255));
        listado6.setText("Total ventas");
        listado6.setAlignmentY(0.0F);
        listado6.setBorder(null);
        listado6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listado6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listado6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listado6MouseExited(evt);
            }
        });
        listado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado6ActionPerformed(evt);
            }
        });
        Panelmenu.add(listado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, 30));

        jPanel1.add(Panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setBackground(new java.awt.Color(21, 101, 192));
    }//GEN-LAST:event_volverMouseExited

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        System.out.println("Se presionó el botón volver");
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        L3.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(false);
        L6.setVisible(false);
   
    }//GEN-LAST:event_volverActionPerformed

    private void listado1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado1MouseEntered
        listado1.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_listado1MouseEntered

    private void listado1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado1MouseExited
        listado1.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_listado1MouseExited

    private void listado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado1ActionPerformed
        System.out.println("Se presionó el botón listado1");
        L1.setVisible(true);
        L2.setVisible(false);
        L3.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(false);
        L6.setVisible(false);
        
    }//GEN-LAST:event_listado1ActionPerformed

    private void idColegio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idColegio2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idColegio2MousePressed

    private void nombreColegio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreColegio1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreColegio1MousePressed

    private void nombreColegio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreColegio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreColegio1ActionPerformed

    private void idColegio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idColegio3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idColegio3MousePressed

    private void listado2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado2MouseEntered
        listado2.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_listado2MouseEntered

    private void listado2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado2MouseExited
        listado2.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_listado2MouseExited

    private void listado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado2ActionPerformed
        System.out.println("listado 2");
        L2.setVisible(true);
        L1.setVisible(false);
        L3.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(false);
        L6.setVisible(false);
    }//GEN-LAST:event_listado2ActionPerformed

    private void listado3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado3MouseEntered
         listado3.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_listado3MouseEntered

    private void listado3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado3MouseExited
         listado3.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_listado3MouseExited

    private void listado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado3ActionPerformed
        System.out.println("listado 3");
        L3.setVisible(true);
        L1.setVisible(false);
        L2.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(false);
        L6.setVisible(false);
    }//GEN-LAST:event_listado3ActionPerformed

    private void listado4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado4MouseEntered
        listado4.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_listado4MouseEntered

    private void listado4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado4MouseExited
        listado4.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_listado4MouseExited

    private void listado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado4ActionPerformed
        System.out.println("listado 4");
        L3.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        L4.setVisible(true);
        L5.setVisible(false);
        L6.setVisible(false);
    }//GEN-LAST:event_listado4ActionPerformed

    private void listado5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado5MouseEntered
         listado5.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_listado5MouseEntered

    private void listado5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado5MouseExited
        listado5.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_listado5MouseExited

    private void listado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado5ActionPerformed
        System.out.println("listado 5");
        L3.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(true);
        L6.setVisible(false);
    }//GEN-LAST:event_listado5ActionPerformed

    private void listado6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado6MouseEntered
        listado6.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_listado6MouseEntered

    private void listado6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado6MouseExited
        listado6.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_listado6MouseExited

    private void listado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado6ActionPerformed
        System.out.println("listado 6");
        L3.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
        L4.setVisible(false);
        L5.setVisible(false);
        L6.setVisible(true);
    }//GEN-LAST:event_listado6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelColegio1;
    private javax.swing.JPanel Panelmenu;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JTextField idColegio2;
    private javax.swing.JTextField idColegio3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton listado1;
    private javax.swing.JButton listado2;
    private javax.swing.JButton listado3;
    private javax.swing.JButton listado4;
    private javax.swing.JButton listado5;
    private javax.swing.JButton listado6;
    private javax.swing.JTextField nombreColegio1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
