/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


/**
 *
 * @author Jess
 */
public class MenuActualizar extends javax.swing.JFrame {

    /**
     * Creates new form IngresarDatos
     */
    public MenuActualizar() {
        initComponents();
    }
    Tabla at = new Tabla();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelColegio1 = new javax.swing.JPanel();
        Title2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        idColegio2 = new javax.swing.JTextField();
        nombreColegio1 = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Title3 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        idColegio3 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Panelmenu = new javax.swing.JPanel();
        titu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        volver = new javax.swing.JButton();
        Actcolegio = new javax.swing.JButton();
        ActProvedor = new javax.swing.JButton();
        ActPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ActProducto = new javax.swing.JButton();
        ActVenta = new javax.swing.JButton();

        PanelColegio1.setBackground(new java.awt.Color(255, 255, 255));

        Title2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title2.setText("Datos Colegio");
        Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Id Colegio");

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));

        idColegio2.setForeground(new java.awt.Color(102, 102, 102));
        idColegio2.setText("Ingresar id del colegio");
        idColegio2.setBorder(null);
        idColegio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idColegio2MousePressed(evt);
            }
        });

        nombreColegio1.setForeground(new java.awt.Color(102, 102, 102));
        nombreColegio1.setText("Ingresar nombre del colegio");
        nombreColegio1.setBorder(null);
        nombreColegio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreColegio1MousePressed(evt);
            }
        });
        nombreColegio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreColegio1ActionPerformed(evt);
            }
        });

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Nombre del Colegio");

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));

        Title3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title3.setText("Datos Uniforme");
        Title3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Id Colegio");

        idColegio3.setForeground(new java.awt.Color(102, 102, 102));
        idColegio3.setText("Ingresar id del colegio");
        idColegio3.setBorder(null);
        idColegio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idColegio3MousePressed(evt);
            }
        });

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));

        javax.swing.GroupLayout PanelColegio1Layout = new javax.swing.GroupLayout(PanelColegio1);
        PanelColegio1.setLayout(PanelColegio1Layout);
        PanelColegio1Layout.setHorizontalGroup(
            PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColegio1Layout.createSequentialGroup()
                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Text7)
                                .addComponent(nombreColegio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Text6)
                                .addComponent(idColegio2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegio1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title2)
                        .addGap(80, 80, 80)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelColegio1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(Title3))
                            .addGroup(PanelColegio1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text8)
                                    .addComponent(idColegio3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelColegio1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGap(308, 308, 308)))
        );
        PanelColegio1Layout.setVerticalGroup(
            PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColegio1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addComponent(Title3)
                        .addGap(18, 18, 18)
                        .addComponent(Text8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idColegio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelColegio1Layout.createSequentialGroup()
                        .addComponent(Title2)
                        .addGap(18, 18, 18)
                        .addComponent(Text6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idColegio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Text7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreColegio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(PanelColegio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelColegio1Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(163, 150));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(844, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelmenu.setBackground(new java.awt.Color(0, 51, 255));
        Panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titu.setForeground(new java.awt.Color(255, 255, 255));
        titu.setText("    ACTUALIZAR ");
        Panelmenu.add(titu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 46));
        Panelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 10));

        volver.setBackground(new java.awt.Color(21, 101, 192));
        volver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("Volver");
        volver.setBorder(null);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        Panelmenu.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 140, 30));

        Actcolegio.setBackground(new java.awt.Color(21, 101, 192));
        Actcolegio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Actcolegio.setForeground(new java.awt.Color(255, 255, 255));
        Actcolegio.setText("Actualizar Colegio");
        Actcolegio.setAlignmentY(0.0F);
        Actcolegio.setBorder(null);
        Actcolegio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actcolegio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActcolegioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActcolegioMouseExited(evt);
            }
        });
        Actcolegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActcolegioActionPerformed(evt);
            }
        });
        Panelmenu.add(Actcolegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 30));

        ActProvedor.setBackground(new java.awt.Color(21, 101, 192));
        ActProvedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ActProvedor.setForeground(new java.awt.Color(255, 255, 255));
        ActProvedor.setText("Actualizar Proveedor");
        ActProvedor.setBorder(null);
        ActProvedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActProvedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActProvedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActProvedorMouseExited(evt);
            }
        });
        ActProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActProvedorActionPerformed(evt);
            }
        });
        Panelmenu.add(ActProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 30));

        ActPedido.setBackground(new java.awt.Color(21, 101, 192));
        ActPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ActPedido.setForeground(new java.awt.Color(255, 255, 255));
        ActPedido.setText("Actualizar Pedido");
        ActPedido.setBorder(null);
        ActPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActPedidoMouseExited(evt);
            }
        });
        ActPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActPedidoActionPerformed(evt);
            }
        });
        Panelmenu.add(ActPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_editar.png"))); // NOI18N
        Panelmenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, 140));

        ActProducto.setBackground(new java.awt.Color(21, 101, 192));
        ActProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ActProducto.setForeground(new java.awt.Color(255, 255, 255));
        ActProducto.setText("Actualizar Producto");
        ActProducto.setBorder(null);
        ActProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActProductoMouseExited(evt);
            }
        });
        ActProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActProductoActionPerformed(evt);
            }
        });
        Panelmenu.add(ActProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 30));

        ActVenta.setBackground(new java.awt.Color(21, 101, 192));
        ActVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ActVenta.setForeground(new java.awt.Color(255, 255, 255));
        ActVenta.setText("Actualizar Venta");
        ActVenta.setBorder(null);
        ActVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActVentaMouseExited(evt);
            }
        });
        ActVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActVentaActionPerformed(evt);
            }
        });
        Panelmenu.add(ActVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 230, 30));

        jPanel1.add(Panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setBackground(new java.awt.Color(21, 101, 192));
    }//GEN-LAST:event_volverMouseExited

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        System.out.println("Se presionó el botón venta");
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        setVisible(false);
        at.setVisible(false);
        
        
        
    }//GEN-LAST:event_volverActionPerformed

    private void ActcolegioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActcolegioMouseEntered
        Actcolegio.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_ActcolegioMouseEntered

    private void ActcolegioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActcolegioMouseExited
        Actcolegio.setBackground(new java.awt.Color(21, 101, 192));
    }//GEN-LAST:event_ActcolegioMouseExited

    private void ActcolegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActcolegioActionPerformed
        System.out.println("Se presionó el botón consultar");
        
        at.setVisible(true);
        
    }//GEN-LAST:event_ActcolegioActionPerformed

    private void ActProvedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActProvedorMouseEntered
        ActProvedor.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_ActProvedorMouseEntered

    private void ActProvedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActProvedorMouseExited
        ActProvedor.setBackground(new java.awt.Color(21, 101, 192));
    }//GEN-LAST:event_ActProvedorMouseExited

    private void ActProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActProvedorActionPerformed
        System.out.println("Se presionó el botón actualizar provedor");
        ActualizarProveedor ap = new ActualizarProveedor();
        ap.setVisible(true);
    }//GEN-LAST:event_ActProvedorActionPerformed

    private void ActPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActPedidoMouseEntered
        ActPedido.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_ActPedidoMouseEntered

    private void ActPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActPedidoMouseExited
        ActPedido.setBackground(new java.awt.Color(21, 101, 192));
    }//GEN-LAST:event_ActPedidoMouseExited

    private void ActPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActPedidoActionPerformed
        System.out.println("Se presionó el botón actualizar pedido");
        ActualizarPedido pd = new ActualizarPedido();
        pd.setVisible(true);
    }//GEN-LAST:event_ActPedidoActionPerformed

    private void ActProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActProductoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ActProductoMouseEntered

    private void ActProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActProductoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ActProductoMouseExited

    private void ActProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActProductoActionPerformed
        System.out.println("Se presionó el botón producto");
        IngresarProducto pd = new IngresarProducto();
        pd.setVisible(true);
    }//GEN-LAST:event_ActProductoActionPerformed

    private void idColegio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idColegio2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idColegio2MousePressed

    private void nombreColegio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreColegio1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreColegio1MousePressed

    private void nombreColegio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreColegio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreColegio1ActionPerformed

    private void idColegio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idColegio3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idColegio3MousePressed

    private void ActVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActVentaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ActVentaMouseEntered

    private void ActVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActVentaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ActVentaMouseExited

    private void ActVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActVentaActionPerformed
        System.out.println("Se presionó el botón venta");
        IngresarVenta pd = new IngresarVenta();
        pd.setVisible(true);
    }//GEN-LAST:event_ActVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActPedido;
    private javax.swing.JButton ActProducto;
    private javax.swing.JButton ActProvedor;
    private javax.swing.JButton ActVenta;
    private javax.swing.JButton Actcolegio;
    private javax.swing.JPanel PanelColegio1;
    private javax.swing.JPanel Panelmenu;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JTextField idColegio2;
    private javax.swing.JTextField idColegio3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nombreColegio1;
    private javax.swing.JLabel titu;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
