
package vistas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.crudsql;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Jess
 */
public class Tablas2 extends javax.swing.JFrame {

    /**
     * Creates new form IngresarColegio
     */
    public Tablas2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    crudsql crud = new crudsql();
    private boolean guardar1Presionado = false;
    private boolean buscarPresionado = false;

    private void actualizarTabla(String id) {
    try {
        ResultSet rs = crud.buscarProductoTerminadoEnInventario(id);

        // Crea el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel(); 
        modelo.addColumn("Codigo");
        modelo.addColumn("Num Pedido");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Cant Existente");
        modelo.addColumn("Sexo");
        modelo.addColumn("Precio Venta");
        modelo.addColumn("Talla");
        modelo.addColumn("Medidad");
      
        while (rs.next()) {
            Object[] fila = new Object[8];
            fila[0] = rs.getString("codigo");
            fila[1] = rs.getInt("num_pedido");
            fila[2] = rs.getString("descripcion");
            fila[3] = rs.getInt("cantidad_existente");
            fila[4] = rs.getString("sexo");
            fila[5] = rs.getDouble("precio_venta");
            fila[6] = rs.getString("talla");
            fila[7] = rs.getString("medidas");
            modelo.addRow(fila);
        }

        // Asigna el modelo a la tabla
        tablaprodu.setModel(modelo);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar tabla: " + e, "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
}
    private void actualizarTabla2(int id) {
    try {
        ResultSet rs = crud.buscarColegioPorId(id);

        // Crea el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel(); 
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Codigo");
        modelo.addColumn("Tipo");
        modelo.addColumn("Caracteristica");
        

      
        while (rs.next()) {
            Object[] fila = new Object[5];
            fila[0] = rs.getInt("id");
            fila[1] = rs.getString("nombre");
            fila[2] = rs.getString("codigo");
            fila[3] = rs.getString("tipo");
            fila[4] = rs.getString("caracteristicas");
            modelo.addRow(fila);
        }

        // Asigna el modelo a la tabla
        tablita1.setModel(modelo);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar tabla: " + e, "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelColegio = new javax.swing.JPanel();
        Text3 = new javax.swing.JLabel();
        Buscar_id = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaprodu = new javax.swing.JTable();
        Text4 = new javax.swing.JLabel();
        Buscaprove = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        bus1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablita1 = new javax.swing.JTable();
        Text5 = new javax.swing.JLabel();
        Buscamat = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        bus2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablita2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 180));
        setUndecorated(true);
        setResizable(false);

        PanelColegio.setBackground(new java.awt.Color(255, 255, 255));
        PanelColegio.setPreferredSize(new java.awt.Dimension(620, 550));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Producto terminado - Inventario");

        Buscar_id.setForeground(new java.awt.Color(102, 102, 102));
        Buscar_id.setText("Ingrese el codigo del producto");
        Buscar_id.setBorder(null);
        Buscar_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Buscar_idMousePressed(evt);
            }
        });
        Buscar_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_idActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(18, 90, 173));
        Modificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setText("MODIFICAR");
        Modificar.setBorder(null);
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarMouseExited(evt);
            }
        });
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 204));

        bus.setBackground(new java.awt.Color(18, 90, 173));
        bus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bus.setForeground(new java.awt.Color(255, 255, 255));
        bus.setText("BUSCAR");
        bus.setBorder(null);
        bus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                busMouseExited(evt);
            }
        });
        bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busActionPerformed(evt);
            }
        });

        tablaprodu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Num pedido", "Descripcion", "Can existente", "Sexo", "Precio venta", "Talla", "Medidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaprodu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaproduAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaprodu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproduMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaprodu);

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Proveedor");

        Buscaprove.setForeground(new java.awt.Color(102, 102, 102));
        Buscaprove.setText("Ingresar nit del proveedor");
        Buscaprove.setBorder(null);
        Buscaprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscaproveMousePressed(evt);
            }
        });
        Buscaprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaproveActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 51, 204));

        bus1.setBackground(new java.awt.Color(18, 90, 173));
        bus1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bus1.setForeground(new java.awt.Color(255, 255, 255));
        bus1.setText("BUSCAR");
        bus1.setBorder(null);
        bus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bus1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bus1MouseExited(evt);
            }
        });
        bus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus1ActionPerformed(evt);
            }
        });

        tablita1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Descripcion", "Can existente", "Uni medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablita1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablita1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablita1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablita1);

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Materia prima");

        Buscamat.setForeground(new java.awt.Color(102, 102, 102));
        Buscamat.setText("Ingresar el codigo de la materia prima");
        Buscamat.setBorder(null);
        Buscamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscamatMousePressed(evt);
            }
        });
        Buscamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscamatActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 51, 204));

        bus2.setBackground(new java.awt.Color(18, 90, 173));
        bus2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bus2.setForeground(new java.awt.Color(255, 255, 255));
        bus2.setText("BUSCAR");
        bus2.setBorder(null);
        bus2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bus2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bus2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bus2MouseExited(evt);
            }
        });
        bus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus2ActionPerformed(evt);
            }
        });

        tablita2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Codigo", "Tipo", "Carateristica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablita2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablita2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablita2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablita2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablita2);

        javax.swing.GroupLayout PanelColegioLayout = new javax.swing.GroupLayout(PanelColegio);
        PanelColegio.setLayout(PanelColegioLayout);
        PanelColegioLayout.setHorizontalGroup(
            PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColegioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(PanelColegioLayout.createSequentialGroup()
                        .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buscar_id, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text3)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text4)
                            .addComponent(Buscaprove, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                                    .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Buscamat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Text5))
                                    .addGap(375, 375, 375))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelColegioLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(bus1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bus2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(PanelColegioLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        PanelColegioLayout.setVerticalGroup(
            PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addComponent(Text3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addComponent(bus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addComponent(Text4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscaprove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addComponent(bus1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                        .addComponent(Text5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bus2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelColegio, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseEntered
        Modificar.setBackground(new java.awt.Color(21, 101, 192));
    }//GEN-LAST:event_ModificarMouseEntered

    private void ModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseExited
        Modificar.setBackground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_ModificarMouseExited

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
       System.out.println("Se presionó el botón modificar");
        if(guardar1Presionado == true){
        int filaSeleccionada = tablaprodu.getSelectedRow();
        if (filaSeleccionada != -1) {
           
                // Obtener datos de la fila seleccionada
                String cod = (String) tablaprodu.getValueAt(filaSeleccionada, 0);
                int num_pedido = Integer.parseInt(tablaprodu.getValueAt(filaSeleccionada, 1).toString());
                String descripcion = (String) tablaprodu.getValueAt(filaSeleccionada, 2);
                int cantidad_existente = Integer.parseInt(tablaprodu.getValueAt(filaSeleccionada, 3).toString());
                String sexo = (String) tablaprodu.getValueAt(filaSeleccionada, 4);
                double precio_venta = Double.parseDouble(tablaprodu.getValueAt(filaSeleccionada, 5).toString());
                String talla = (String) tablaprodu.getValueAt(filaSeleccionada, 6);
                String medidas = (String) tablaprodu.getValueAt(filaSeleccionada, 7);

                 
        }
           
        }else{
            if(buscarPresionado == true){
                System.out.println("se presiono buscar true");
                int filaSeleccionada2 = tablita1.getSelectedRow();
                if (filaSeleccionada2 != -1) {
                    // Obtener datos de la fila seleccionada
                    int idc = Integer.parseInt(tablita1.getValueAt(filaSeleccionada2, 0).toString());
                    String nombrec = (String) tablita1.getValueAt(filaSeleccionada2, 1);
                    String codu = (String) tablita1.getValueAt(filaSeleccionada2, 2);
                    String tipo = (String) tablita1.getValueAt(filaSeleccionada2, 3);
                    String car = (String) tablita1.getValueAt(filaSeleccionada2, 4);
                    // Abrir la ventana de edición
                    crud.editarColegio(idc, nombrec);
                    crud.editarUniforme(codu, idc, tipo, car);
                }
            }
        }
        Buscar_id.setText("Ingresar id del cliente");
        DefaultTableModel modelo = (DefaultTableModel) tablaprodu.getModel();
        modelo.setRowCount(0);

        setVisible(false);

    }//GEN-LAST:event_ModificarActionPerformed

    private void Buscar_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscar_idMousePressed
        if(Buscar_id.getText().equals("Ingrese el codigo del producto"));
        Buscar_id.setText("");
    }//GEN-LAST:event_Buscar_idMousePressed

    private void busMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_busMouseEntered

    private void busMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_busMouseExited

    private void busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busActionPerformed
        guardar1Presionado = true;
        buscarPresionado = false;
        actualizarTabla(Buscar_id.getText());
         
         
    }//GEN-LAST:event_busActionPerformed

    private void tablaproduAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaproduAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaproduAncestorAdded

    private void tablaproduMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproduMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaproduMouseClicked

    private void BuscaproveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaproveMousePressed
        if(Buscaprove.getText().equals("Ingresar nit del proveedor"));
           Buscaprove.setText("");
    }//GEN-LAST:event_BuscaproveMousePressed

    private void bus1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bus1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bus1MouseEntered

    private void bus1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bus1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bus1MouseExited

    private void bus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus1ActionPerformed
        System.out.println("Se presionó el botón BUSCAR C");
        buscarPresionado = true;
        guardar1Presionado = false;
        int xd = Integer.parseInt(Buscaprove.getText());
        actualizarTabla2(xd);
        
    }//GEN-LAST:event_bus1ActionPerformed

    private void tablita1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablita1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablita1AncestorAdded

    private void tablita1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablita1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablita1MouseClicked

    private void Buscar_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar_idActionPerformed

    private void BuscaproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaproveActionPerformed

    private void BuscamatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscamatMousePressed
        if(Buscamat.getText().equals("Ingresar el codigo de la materia prima"));
           Buscamat.setText("");
    }//GEN-LAST:event_BuscamatMousePressed

    private void BuscamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscamatActionPerformed

    private void bus2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bus2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bus2MouseEntered

    private void bus2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bus2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bus2MouseExited

    private void bus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bus2ActionPerformed

    private void tablita2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablita2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablita2AncestorAdded

    private void tablita2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablita2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablita2MouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarColegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscamat;
    private javax.swing.JTextField Buscaprove;
    private javax.swing.JTextField Buscar_id;
    private javax.swing.JButton Modificar;
    private javax.swing.JPanel PanelColegio;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JButton bus;
    private javax.swing.JButton bus1;
    private javax.swing.JButton bus2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tablaprodu;
    private javax.swing.JTable tablita1;
    private javax.swing.JTable tablita2;
    // End of variables declaration//GEN-END:variables
}
